version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    ports:
      - '80:80'
  foo:
    image: 263108651745.dkr.ecr.ap-southeast-2.amazonaws.com/foo-ecrrepo
    build: ./foo
    expose:
      - '8080'
    networks:
      my-network:
        aliases:
          - foo
  boo:
    image: 263108651745.dkr.ecr.ap-southeast-2.amazonaws.com/boo-ecrrepo
    build: ./boo
    expose:
      - '8080'
    networks:
      my-network:
        aliases:
          - boo
networks:
  my-network:
