version: '3'
services:
  nginx:
    image: nginx:1.13.7
    container_name: nginx
    depends_on:
      - foo
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-network
    ports:
      - '80:80'
  foo:
    build: .
    ports:
      - '8080:8080'
    networks:
      my-network:
        aliases:
          - foo
networks:
  my-network:
